require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AssignedFoldersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # AssignedFolder. As you add validations to AssignedFolder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssignedFoldersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all assigned_folders as @assigned_folders" do
      assigned_folder = AssignedFolder.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:assigned_folders)).to eq([assigned_folder])
    end
  end

  describe "GET #show" do
    it "assigns the requested assigned_folder as @assigned_folder" do
      assigned_folder = AssignedFolder.create! valid_attributes
      get :show, {:id => assigned_folder.to_param}, valid_session
      expect(assigns(:assigned_folder)).to eq(assigned_folder)
    end
  end

  describe "GET #new" do
    it "assigns a new assigned_folder as @assigned_folder" do
      get :new, {}, valid_session
      expect(assigns(:assigned_folder)).to be_a_new(AssignedFolder)
    end
  end

  describe "GET #edit" do
    it "assigns the requested assigned_folder as @assigned_folder" do
      assigned_folder = AssignedFolder.create! valid_attributes
      get :edit, {:id => assigned_folder.to_param}, valid_session
      expect(assigns(:assigned_folder)).to eq(assigned_folder)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AssignedFolder" do
        expect {
          post :create, {:assigned_folder => valid_attributes}, valid_session
        }.to change(AssignedFolder, :count).by(1)
      end

      it "assigns a newly created assigned_folder as @assigned_folder" do
        post :create, {:assigned_folder => valid_attributes}, valid_session
        expect(assigns(:assigned_folder)).to be_a(AssignedFolder)
        expect(assigns(:assigned_folder)).to be_persisted
      end

      it "redirects to the created assigned_folder" do
        post :create, {:assigned_folder => valid_attributes}, valid_session
        expect(response).to redirect_to(AssignedFolder.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved assigned_folder as @assigned_folder" do
        post :create, {:assigned_folder => invalid_attributes}, valid_session
        expect(assigns(:assigned_folder)).to be_a_new(AssignedFolder)
      end

      it "re-renders the 'new' template" do
        post :create, {:assigned_folder => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested assigned_folder" do
        assigned_folder = AssignedFolder.create! valid_attributes
        put :update, {:id => assigned_folder.to_param, :assigned_folder => new_attributes}, valid_session
        assigned_folder.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested assigned_folder as @assigned_folder" do
        assigned_folder = AssignedFolder.create! valid_attributes
        put :update, {:id => assigned_folder.to_param, :assigned_folder => valid_attributes}, valid_session
        expect(assigns(:assigned_folder)).to eq(assigned_folder)
      end

      it "redirects to the assigned_folder" do
        assigned_folder = AssignedFolder.create! valid_attributes
        put :update, {:id => assigned_folder.to_param, :assigned_folder => valid_attributes}, valid_session
        expect(response).to redirect_to(assigned_folder)
      end
    end

    context "with invalid params" do
      it "assigns the assigned_folder as @assigned_folder" do
        assigned_folder = AssignedFolder.create! valid_attributes
        put :update, {:id => assigned_folder.to_param, :assigned_folder => invalid_attributes}, valid_session
        expect(assigns(:assigned_folder)).to eq(assigned_folder)
      end

      it "re-renders the 'edit' template" do
        assigned_folder = AssignedFolder.create! valid_attributes
        put :update, {:id => assigned_folder.to_param, :assigned_folder => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested assigned_folder" do
      assigned_folder = AssignedFolder.create! valid_attributes
      expect {
        delete :destroy, {:id => assigned_folder.to_param}, valid_session
      }.to change(AssignedFolder, :count).by(-1)
    end

    it "redirects to the assigned_folders list" do
      assigned_folder = AssignedFolder.create! valid_attributes
      delete :destroy, {:id => assigned_folder.to_param}, valid_session
      expect(response).to redirect_to(assigned_folders_url)
    end
  end

end
