require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BoardingRequisitionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BoardingRequisition. As you add validations to BoardingRequisition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoardingRequisitionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all boarding_requisitions as @boarding_requisitions" do
      boarding_requisition = BoardingRequisition.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:boarding_requisitions)).to eq([boarding_requisition])
    end
  end

  describe "GET #show" do
    it "assigns the requested boarding_requisition as @boarding_requisition" do
      boarding_requisition = BoardingRequisition.create! valid_attributes
      get :show, {:id => boarding_requisition.to_param}, valid_session
      expect(assigns(:boarding_requisition)).to eq(boarding_requisition)
    end
  end

  describe "GET #new" do
    it "assigns a new boarding_requisition as @boarding_requisition" do
      get :new, {}, valid_session
      expect(assigns(:boarding_requisition)).to be_a_new(BoardingRequisition)
    end
  end

  describe "GET #edit" do
    it "assigns the requested boarding_requisition as @boarding_requisition" do
      boarding_requisition = BoardingRequisition.create! valid_attributes
      get :edit, {:id => boarding_requisition.to_param}, valid_session
      expect(assigns(:boarding_requisition)).to eq(boarding_requisition)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BoardingRequisition" do
        expect {
          post :create, {:boarding_requisition => valid_attributes}, valid_session
        }.to change(BoardingRequisition, :count).by(1)
      end

      it "assigns a newly created boarding_requisition as @boarding_requisition" do
        post :create, {:boarding_requisition => valid_attributes}, valid_session
        expect(assigns(:boarding_requisition)).to be_a(BoardingRequisition)
        expect(assigns(:boarding_requisition)).to be_persisted
      end

      it "redirects to the created boarding_requisition" do
        post :create, {:boarding_requisition => valid_attributes}, valid_session
        expect(response).to redirect_to(BoardingRequisition.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved boarding_requisition as @boarding_requisition" do
        post :create, {:boarding_requisition => invalid_attributes}, valid_session
        expect(assigns(:boarding_requisition)).to be_a_new(BoardingRequisition)
      end

      it "re-renders the 'new' template" do
        post :create, {:boarding_requisition => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested boarding_requisition" do
        boarding_requisition = BoardingRequisition.create! valid_attributes
        put :update, {:id => boarding_requisition.to_param, :boarding_requisition => new_attributes}, valid_session
        boarding_requisition.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested boarding_requisition as @boarding_requisition" do
        boarding_requisition = BoardingRequisition.create! valid_attributes
        put :update, {:id => boarding_requisition.to_param, :boarding_requisition => valid_attributes}, valid_session
        expect(assigns(:boarding_requisition)).to eq(boarding_requisition)
      end

      it "redirects to the boarding_requisition" do
        boarding_requisition = BoardingRequisition.create! valid_attributes
        put :update, {:id => boarding_requisition.to_param, :boarding_requisition => valid_attributes}, valid_session
        expect(response).to redirect_to(boarding_requisition)
      end
    end

    context "with invalid params" do
      it "assigns the boarding_requisition as @boarding_requisition" do
        boarding_requisition = BoardingRequisition.create! valid_attributes
        put :update, {:id => boarding_requisition.to_param, :boarding_requisition => invalid_attributes}, valid_session
        expect(assigns(:boarding_requisition)).to eq(boarding_requisition)
      end

      it "re-renders the 'edit' template" do
        boarding_requisition = BoardingRequisition.create! valid_attributes
        put :update, {:id => boarding_requisition.to_param, :boarding_requisition => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested boarding_requisition" do
      boarding_requisition = BoardingRequisition.create! valid_attributes
      expect {
        delete :destroy, {:id => boarding_requisition.to_param}, valid_session
      }.to change(BoardingRequisition, :count).by(-1)
    end

    it "redirects to the boarding_requisitions list" do
      boarding_requisition = BoardingRequisition.create! valid_attributes
      delete :destroy, {:id => boarding_requisition.to_param}, valid_session
      expect(response).to redirect_to(boarding_requisitions_url)
    end
  end

end
