require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JobEducationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # JobEducation. As you add validations to JobEducation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JobEducationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all job_educations as @job_educations" do
      job_education = JobEducation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:job_educations)).to eq([job_education])
    end
  end

  describe "GET #show" do
    it "assigns the requested job_education as @job_education" do
      job_education = JobEducation.create! valid_attributes
      get :show, {:id => job_education.to_param}, valid_session
      expect(assigns(:job_education)).to eq(job_education)
    end
  end

  describe "GET #new" do
    it "assigns a new job_education as @job_education" do
      get :new, {}, valid_session
      expect(assigns(:job_education)).to be_a_new(JobEducation)
    end
  end

  describe "GET #edit" do
    it "assigns the requested job_education as @job_education" do
      job_education = JobEducation.create! valid_attributes
      get :edit, {:id => job_education.to_param}, valid_session
      expect(assigns(:job_education)).to eq(job_education)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new JobEducation" do
        expect {
          post :create, {:job_education => valid_attributes}, valid_session
        }.to change(JobEducation, :count).by(1)
      end

      it "assigns a newly created job_education as @job_education" do
        post :create, {:job_education => valid_attributes}, valid_session
        expect(assigns(:job_education)).to be_a(JobEducation)
        expect(assigns(:job_education)).to be_persisted
      end

      it "redirects to the created job_education" do
        post :create, {:job_education => valid_attributes}, valid_session
        expect(response).to redirect_to(JobEducation.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved job_education as @job_education" do
        post :create, {:job_education => invalid_attributes}, valid_session
        expect(assigns(:job_education)).to be_a_new(JobEducation)
      end

      it "re-renders the 'new' template" do
        post :create, {:job_education => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested job_education" do
        job_education = JobEducation.create! valid_attributes
        put :update, {:id => job_education.to_param, :job_education => new_attributes}, valid_session
        job_education.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested job_education as @job_education" do
        job_education = JobEducation.create! valid_attributes
        put :update, {:id => job_education.to_param, :job_education => valid_attributes}, valid_session
        expect(assigns(:job_education)).to eq(job_education)
      end

      it "redirects to the job_education" do
        job_education = JobEducation.create! valid_attributes
        put :update, {:id => job_education.to_param, :job_education => valid_attributes}, valid_session
        expect(response).to redirect_to(job_education)
      end
    end

    context "with invalid params" do
      it "assigns the job_education as @job_education" do
        job_education = JobEducation.create! valid_attributes
        put :update, {:id => job_education.to_param, :job_education => invalid_attributes}, valid_session
        expect(assigns(:job_education)).to eq(job_education)
      end

      it "re-renders the 'edit' template" do
        job_education = JobEducation.create! valid_attributes
        put :update, {:id => job_education.to_param, :job_education => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested job_education" do
      job_education = JobEducation.create! valid_attributes
      expect {
        delete :destroy, {:id => job_education.to_param}, valid_session
      }.to change(JobEducation, :count).by(-1)
    end

    it "redirects to the job_educations list" do
      job_education = JobEducation.create! valid_attributes
      delete :destroy, {:id => job_education.to_param}, valid_session
      expect(response).to redirect_to(job_educations_url)
    end
  end

end
