require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OfferRequisitionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # OfferRequisition. As you add validations to OfferRequisition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OfferRequisitionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all offer_requisitions as @offer_requisitions" do
      offer_requisition = OfferRequisition.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:offer_requisitions)).to eq([offer_requisition])
    end
  end

  describe "GET #show" do
    it "assigns the requested offer_requisition as @offer_requisition" do
      offer_requisition = OfferRequisition.create! valid_attributes
      get :show, {:id => offer_requisition.to_param}, valid_session
      expect(assigns(:offer_requisition)).to eq(offer_requisition)
    end
  end

  describe "GET #new" do
    it "assigns a new offer_requisition as @offer_requisition" do
      get :new, {}, valid_session
      expect(assigns(:offer_requisition)).to be_a_new(OfferRequisition)
    end
  end

  describe "GET #edit" do
    it "assigns the requested offer_requisition as @offer_requisition" do
      offer_requisition = OfferRequisition.create! valid_attributes
      get :edit, {:id => offer_requisition.to_param}, valid_session
      expect(assigns(:offer_requisition)).to eq(offer_requisition)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new OfferRequisition" do
        expect {
          post :create, {:offer_requisition => valid_attributes}, valid_session
        }.to change(OfferRequisition, :count).by(1)
      end

      it "assigns a newly created offer_requisition as @offer_requisition" do
        post :create, {:offer_requisition => valid_attributes}, valid_session
        expect(assigns(:offer_requisition)).to be_a(OfferRequisition)
        expect(assigns(:offer_requisition)).to be_persisted
      end

      it "redirects to the created offer_requisition" do
        post :create, {:offer_requisition => valid_attributes}, valid_session
        expect(response).to redirect_to(OfferRequisition.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved offer_requisition as @offer_requisition" do
        post :create, {:offer_requisition => invalid_attributes}, valid_session
        expect(assigns(:offer_requisition)).to be_a_new(OfferRequisition)
      end

      it "re-renders the 'new' template" do
        post :create, {:offer_requisition => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested offer_requisition" do
        offer_requisition = OfferRequisition.create! valid_attributes
        put :update, {:id => offer_requisition.to_param, :offer_requisition => new_attributes}, valid_session
        offer_requisition.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested offer_requisition as @offer_requisition" do
        offer_requisition = OfferRequisition.create! valid_attributes
        put :update, {:id => offer_requisition.to_param, :offer_requisition => valid_attributes}, valid_session
        expect(assigns(:offer_requisition)).to eq(offer_requisition)
      end

      it "redirects to the offer_requisition" do
        offer_requisition = OfferRequisition.create! valid_attributes
        put :update, {:id => offer_requisition.to_param, :offer_requisition => valid_attributes}, valid_session
        expect(response).to redirect_to(offer_requisition)
      end
    end

    context "with invalid params" do
      it "assigns the offer_requisition as @offer_requisition" do
        offer_requisition = OfferRequisition.create! valid_attributes
        put :update, {:id => offer_requisition.to_param, :offer_requisition => invalid_attributes}, valid_session
        expect(assigns(:offer_requisition)).to eq(offer_requisition)
      end

      it "re-renders the 'edit' template" do
        offer_requisition = OfferRequisition.create! valid_attributes
        put :update, {:id => offer_requisition.to_param, :offer_requisition => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested offer_requisition" do
      offer_requisition = OfferRequisition.create! valid_attributes
      expect {
        delete :destroy, {:id => offer_requisition.to_param}, valid_session
      }.to change(OfferRequisition, :count).by(-1)
    end

    it "redirects to the offer_requisitions list" do
      offer_requisition = OfferRequisition.create! valid_attributes
      delete :destroy, {:id => offer_requisition.to_param}, valid_session
      expect(response).to redirect_to(offer_requisitions_url)
    end
  end

end
