require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SavedJobSearchesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SavedJobSearch. As you add validations to SavedJobSearch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SavedJobSearchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all saved_job_searches as @saved_job_searches" do
      saved_job_search = SavedJobSearch.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:saved_job_searches)).to eq([saved_job_search])
    end
  end

  describe "GET #show" do
    it "assigns the requested saved_job_search as @saved_job_search" do
      saved_job_search = SavedJobSearch.create! valid_attributes
      get :show, {:id => saved_job_search.to_param}, valid_session
      expect(assigns(:saved_job_search)).to eq(saved_job_search)
    end
  end

  describe "GET #new" do
    it "assigns a new saved_job_search as @saved_job_search" do
      get :new, {}, valid_session
      expect(assigns(:saved_job_search)).to be_a_new(SavedJobSearch)
    end
  end

  describe "GET #edit" do
    it "assigns the requested saved_job_search as @saved_job_search" do
      saved_job_search = SavedJobSearch.create! valid_attributes
      get :edit, {:id => saved_job_search.to_param}, valid_session
      expect(assigns(:saved_job_search)).to eq(saved_job_search)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SavedJobSearch" do
        expect {
          post :create, {:saved_job_search => valid_attributes}, valid_session
        }.to change(SavedJobSearch, :count).by(1)
      end

      it "assigns a newly created saved_job_search as @saved_job_search" do
        post :create, {:saved_job_search => valid_attributes}, valid_session
        expect(assigns(:saved_job_search)).to be_a(SavedJobSearch)
        expect(assigns(:saved_job_search)).to be_persisted
      end

      it "redirects to the created saved_job_search" do
        post :create, {:saved_job_search => valid_attributes}, valid_session
        expect(response).to redirect_to(SavedJobSearch.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved saved_job_search as @saved_job_search" do
        post :create, {:saved_job_search => invalid_attributes}, valid_session
        expect(assigns(:saved_job_search)).to be_a_new(SavedJobSearch)
      end

      it "re-renders the 'new' template" do
        post :create, {:saved_job_search => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested saved_job_search" do
        saved_job_search = SavedJobSearch.create! valid_attributes
        put :update, {:id => saved_job_search.to_param, :saved_job_search => new_attributes}, valid_session
        saved_job_search.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested saved_job_search as @saved_job_search" do
        saved_job_search = SavedJobSearch.create! valid_attributes
        put :update, {:id => saved_job_search.to_param, :saved_job_search => valid_attributes}, valid_session
        expect(assigns(:saved_job_search)).to eq(saved_job_search)
      end

      it "redirects to the saved_job_search" do
        saved_job_search = SavedJobSearch.create! valid_attributes
        put :update, {:id => saved_job_search.to_param, :saved_job_search => valid_attributes}, valid_session
        expect(response).to redirect_to(saved_job_search)
      end
    end

    context "with invalid params" do
      it "assigns the saved_job_search as @saved_job_search" do
        saved_job_search = SavedJobSearch.create! valid_attributes
        put :update, {:id => saved_job_search.to_param, :saved_job_search => invalid_attributes}, valid_session
        expect(assigns(:saved_job_search)).to eq(saved_job_search)
      end

      it "re-renders the 'edit' template" do
        saved_job_search = SavedJobSearch.create! valid_attributes
        put :update, {:id => saved_job_search.to_param, :saved_job_search => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested saved_job_search" do
      saved_job_search = SavedJobSearch.create! valid_attributes
      expect {
        delete :destroy, {:id => saved_job_search.to_param}, valid_session
      }.to change(SavedJobSearch, :count).by(-1)
    end

    it "redirects to the saved_job_searches list" do
      saved_job_search = SavedJobSearch.create! valid_attributes
      delete :destroy, {:id => saved_job_search.to_param}, valid_session
      expect(response).to redirect_to(saved_job_searches_url)
    end
  end

end
