require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SharedJobseekersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SharedJobseeker. As you add validations to SharedJobseeker, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SharedJobseekersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all shared_jobseekers as @shared_jobseekers" do
      shared_jobseeker = SharedJobseeker.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:shared_jobseekers)).to eq([shared_jobseeker])
    end
  end

  describe "GET #show" do
    it "assigns the requested shared_jobseeker as @shared_jobseeker" do
      shared_jobseeker = SharedJobseeker.create! valid_attributes
      get :show, {:id => shared_jobseeker.to_param}, valid_session
      expect(assigns(:shared_jobseeker)).to eq(shared_jobseeker)
    end
  end

  describe "GET #new" do
    it "assigns a new shared_jobseeker as @shared_jobseeker" do
      get :new, {}, valid_session
      expect(assigns(:shared_jobseeker)).to be_a_new(SharedJobseeker)
    end
  end

  describe "GET #edit" do
    it "assigns the requested shared_jobseeker as @shared_jobseeker" do
      shared_jobseeker = SharedJobseeker.create! valid_attributes
      get :edit, {:id => shared_jobseeker.to_param}, valid_session
      expect(assigns(:shared_jobseeker)).to eq(shared_jobseeker)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SharedJobseeker" do
        expect {
          post :create, {:shared_jobseeker => valid_attributes}, valid_session
        }.to change(SharedJobseeker, :count).by(1)
      end

      it "assigns a newly created shared_jobseeker as @shared_jobseeker" do
        post :create, {:shared_jobseeker => valid_attributes}, valid_session
        expect(assigns(:shared_jobseeker)).to be_a(SharedJobseeker)
        expect(assigns(:shared_jobseeker)).to be_persisted
      end

      it "redirects to the created shared_jobseeker" do
        post :create, {:shared_jobseeker => valid_attributes}, valid_session
        expect(response).to redirect_to(SharedJobseeker.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved shared_jobseeker as @shared_jobseeker" do
        post :create, {:shared_jobseeker => invalid_attributes}, valid_session
        expect(assigns(:shared_jobseeker)).to be_a_new(SharedJobseeker)
      end

      it "re-renders the 'new' template" do
        post :create, {:shared_jobseeker => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shared_jobseeker" do
        shared_jobseeker = SharedJobseeker.create! valid_attributes
        put :update, {:id => shared_jobseeker.to_param, :shared_jobseeker => new_attributes}, valid_session
        shared_jobseeker.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested shared_jobseeker as @shared_jobseeker" do
        shared_jobseeker = SharedJobseeker.create! valid_attributes
        put :update, {:id => shared_jobseeker.to_param, :shared_jobseeker => valid_attributes}, valid_session
        expect(assigns(:shared_jobseeker)).to eq(shared_jobseeker)
      end

      it "redirects to the shared_jobseeker" do
        shared_jobseeker = SharedJobseeker.create! valid_attributes
        put :update, {:id => shared_jobseeker.to_param, :shared_jobseeker => valid_attributes}, valid_session
        expect(response).to redirect_to(shared_jobseeker)
      end
    end

    context "with invalid params" do
      it "assigns the shared_jobseeker as @shared_jobseeker" do
        shared_jobseeker = SharedJobseeker.create! valid_attributes
        put :update, {:id => shared_jobseeker.to_param, :shared_jobseeker => invalid_attributes}, valid_session
        expect(assigns(:shared_jobseeker)).to eq(shared_jobseeker)
      end

      it "re-renders the 'edit' template" do
        shared_jobseeker = SharedJobseeker.create! valid_attributes
        put :update, {:id => shared_jobseeker.to_param, :shared_jobseeker => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested shared_jobseeker" do
      shared_jobseeker = SharedJobseeker.create! valid_attributes
      expect {
        delete :destroy, {:id => shared_jobseeker.to_param}, valid_session
      }.to change(SharedJobseeker, :count).by(-1)
    end

    it "redirects to the shared_jobseekers list" do
      shared_jobseeker = SharedJobseeker.create! valid_attributes
      delete :destroy, {:id => shared_jobseeker.to_param}, valid_session
      expect(response).to redirect_to(shared_jobseekers_url)
    end
  end

end
